name: Perioding healthcheck ping

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://mycicdtestapp.herokuapp.com/version
          max-attempts: 3
          retry-delay: 10s